### ISSUE TITLE
To-Do with Fetch

### ISSUE THREAD

**Issue by Moyrasc** [Emanuel4Geeks/Todolist-Application-Using-React-and-Fetch#5]
Buen trabajo, Emanuel

En estas parte :
![image](https://user-images.githubusercontent.com/88618857/216760215-7709f9d6-8447-4569-bb38-dea2a12961f0.png)

línea 65 a la 67, gran trabajo documentando tu código, tienes toda la razón :)

Sigue así!

**Comment by emanuel-c4** [comment]
Es la documentación según JSDoc que se usa para la correcta descripción del funcionamiento de las funciones.
